### ISSUE TITLE
Brands attr

### ISSUE THREAD

**Issue by streamia-livestreaming** [madrasthemes/mas-woocommerce-brands#31]
Platform: Version 6.1.1.
Theme: Electro 2.7.2.
License: Envato.

Brands attribute does not save image.
It even does not change image on existing (demo) Brands.
Any ideas?

**Comment by lextc** [comment]
after installing the plugin, I had the same problem, and is easy to fix.
Just go to WooCommerce > Settings > Products > Brands and select the brand attribute, then refresh your page

Like in this screenshot: https://ps.w.org/mas-woocommerce-brands/assets/screenshot-1.png?rev=2265591 (taken from the theme manual).
